export { analyzeProjectSourceTexts, analyzeSourceText } from "./entry/scan.js";
export { analyzeCssSources } from "./pipeline/css-analysis/index.js";
export {
  buildLanguageFrontends,
  buildSourceFrontendFactsFromSourceFiles,
  buildSourceFrontendFactsFromParsedFiles,
} from "./pipeline/language-frontends/index.js";
export {
  buildFactGraph,
  graphToSelectorEntries,
  graphToReachabilityStylesheets,
  graphToReactRenderSyntaxInputs,
  graphToStylesheetFilePaths,
} from "./pipeline/fact-graph/index.js";
export { evaluateSymbolicExpressions } from "./pipeline/symbolic-evaluation/index.js";
export { buildRenderStructure } from "./pipeline/render-structure/index.js";
export { buildModuleFacts } from "./pipeline/module-facts/buildModuleFacts.js";
export {
  collectAvailableExportedNames,
  getAllResolvedModuleFacts,
  getAnalyzedModuleFilePaths,
  getDirectSourceImportFacts,
  getDirectStylesheetImportFacts,
  getResolvedModuleFacts,
  resolveModuleFactExport,
  resolveModuleFactSourceSpecifier,
  resolveSourceSpecifier,
} from "./pipeline/module-facts/index.js";
export {
  buildProjectBindingResolution,
  collectSourceSymbols,
  createSymbolId,
  getExportedExpressionBindingsForFile,
  getCssModuleBindingsForFile,
  getImportedBindingsForFile,
  getImportedComponentBindingsForFile,
  getImportedExpressionBindingsBySymbolIdForFile,
  getLocalAliasAt,
  getLocalAliasResolutionsForFile,
  getNamespaceImportsForFile,
  getScopeAt,
  getSymbol,
  getSymbolAt,
  getSymbolReferenceAt,
  getSymbolResolutionFilePaths,
  resolveAliasedSymbol,
  resolveLocalAliasAt,
  resolveReferenceAt,
  resolveCssModuleMember,
  resolveCssModuleMemberAccess,
  resolveCssModuleNamespace,
  resolveExportedTypeDeclaration,
  resolveExportedTypeBinding,
  resolveTypeDeclaration,
  resolveTypeBinding,
} from "./pipeline/symbol-resolution/index.js";
export { toAbstractClassSet } from "./pipeline/symbolic-evaluation/class-values/index.js";
export { toClassExpressionSummary } from "./pipeline/symbolic-evaluation/index.js";
export { buildExternalCssSummary } from "./pipeline/external-css/index.js";
export {
  buildProjectSelectorProjection,
  buildSelectorReachability,
  selectorBranchSourceKey,
} from "./pipeline/selector-reachability/index.js";
export {
  buildOwnershipInference,
  classDefinitionConsumerEvidenceId,
  classOwnershipEvidenceId,
  ownershipInferenceDiagnosticId,
  styleClassificationEvidenceId,
  styleOwnerCandidateId,
  stylesheetOwnershipEvidenceId,
} from "./pipeline/ownership-inference/index.js";
export {
  buildProjectEvidence,
  buildProjectEvidenceEntities,
  buildProjectEvidenceRelations,
  projectEvidenceDiagnosticId,
  stylesheetReachabilityEvidenceId,
} from "./pipeline/project-evidence/index.js";
export { buildReachabilitySummary } from "./pipeline/reachability/index.js";
export type { EngineModuleId, EngineSymbolId, SourceAnchor } from "./types/core.js";
export type {
  CssAtRuleContextFact,
  CssClassContextFact,
  CssClassDefinitionFact,
  CssDeclarationFact,
  CssSelectorBranchFact,
  CssSelectorMatchKind,
  CssStyleRuleFact,
} from "./types/css.js";
export type {
  AnalysisCertainty,
  AnalysisConfidence,
  AnalysisDecision,
  AnalysisDimensionState,
  AnalysisSeverity,
  AnalysisStatus,
  AnalysisTrace,
  AnalysisTraceCategory,
} from "./types/analysis.js";
export type {
  AnalysisEvidence,
  AnalysisProgressCallback,
  AnalysisProgressEvent,
  AnalysisProgressStatus,
  StaticAnalysisEngineResult,
} from "./types/runtime.js";
export type { ExperimentalCssFileAnalysis } from "./pipeline/css-analysis/index.js";
export type {
  CssFrontendFacts,
  CssFrontendFile,
  LanguageFrontendsInput,
  LanguageFrontendsResult,
  RuntimeDomClassSite,
  RuntimeDomClassSiteKind,
  RuntimeDomLibraryHint,
  SourceFrontendFacts,
  SourceFrontendFile,
  SourceLanguageKind,
  SourceModuleSyntaxFacts,
} from "./pipeline/language-frontends/index.js";
export type {
  FactEdge,
  FactEdgeId,
  FactGraph,
  FactGraphDiagnostic,
  FactGraphResult,
  FactNode,
  FactNodeId,
  FactProvenance,
  FileResourceNode,
  ContainsEdge,
  DefinesSelectorEdge,
  ModuleNode,
  OriginatesFromFileEdge,
  RuleDefinitionNode,
  SelectorBranchNode,
  SelectorNode,
  StyleSheetNode,
} from "./pipeline/fact-graph/index.js";
export type {
  CanonicalClassExpression,
  CanonicalExpressionKind,
  Certainty,
  ClassEmissionVariant,
  ConditionFact,
  ConditionId,
  CssModuleClassContribution,
  EvaluatedExpressionFacts,
  EvaluatedExpressionId,
  EvaluatedExpressionIndexes,
  ExternalClassContribution,
  SymbolicEvaluationDiagnostic,
  SymbolicEvaluationInput,
  SymbolicEvaluationOptions,
  SymbolicEvaluationProvenance,
  SymbolicEvaluationResult,
  TokenAlternative,
  UnsupportedReason,
  UnsupportedReasonCode,
} from "./pipeline/symbolic-evaluation/index.js";
export type {
  EmissionSite,
  EmissionSiteId,
  EmissionTokenProvenance,
  PlacementCondition,
  PlacementConditionId,
  RenderCertainty,
  RenderComponentId,
  RenderedComponent,
  RenderedComponentBoundary,
  RenderedComponentBoundaryId,
  RenderedElement,
  RenderedElementId,
  RenderGraphProjection,
  RenderGraphProjectionEdge,
  RenderGraphProjectionNode,
  RenderModel,
  RenderModelIndexes,
  RenderModelMeta,
  RenderPath,
  RenderPathId,
  RenderPathSegment,
  RenderRegion as RenderStructureRegion,
  RenderRegionId,
  RenderStructureDiagnostic,
  RenderStructureInput,
  RenderStructureOptions,
  RenderStructureProvenance,
  RenderStructureResult,
  UnsupportedClassReferenceDiagnostic,
  UnsupportedClassReferenceReason,
} from "./pipeline/render-structure/index.js";
export type {
  ActiveExternalCssProvider,
  ExternalCssAnalysisInput,
  ExternalCssGlobalProviderConfig,
  ExternalCssSummary,
} from "./pipeline/external-css/index.js";
export type {
  HtmlStylesheetLinkFact,
  HtmlStylesheetLinkInput,
} from "./pipeline/workspace-discovery/index.js";
export type {
  RenderGraphProjection as RenderGraph,
  RenderGraphProjectionEdge as RenderGraphEdge,
  RenderGraphProjectionNode as RenderGraphNode,
} from "./pipeline/render-structure/index.js";
export type {
  ReachabilityAvailability,
  ReachabilitySummary,
  StylesheetReachabilityContext,
  StylesheetReachabilityContextRecord,
  StylesheetReachabilityRecord,
} from "./pipeline/reachability/index.js";
export type {
  ModuleFacts,
  ModuleFactsImportKind,
  ResolvedModuleFacts,
} from "./pipeline/module-facts/index.js";
export type {
  EngineSymbol,
  LocalAliasResolution,
  ProjectBindingResolution,
  ScopeId,
  ScopeKind,
  ResolvedCssModuleBindingsForFile,
  ResolvedCssModuleBindingDiagnostic,
  ResolvedCssModuleImport,
  ResolvedCssModuleMemberAccessResult,
  ResolvedCssModuleMemberBinding,
  ResolvedCssModuleMemberReference,
  ResolvedCssModuleNamespaceBinding,
  ResolvedImportedBinding,
  ResolvedNamespaceMemberResult,
  ResolvedNamespaceImport,
  ResolvedProjectExport,
  ResolvedTypeDeclaration,
  ResolvedTypeBinding,
  SourceScope,
  SymbolReference,
  SymbolSpace,
  SymbolResolutionReason,
  SymbolKind,
} from "./pipeline/symbol-resolution/index.js";
export type {
  AbstractClassSet,
  AbstractValue,
  ClassDerivationStep,
  ClassExpressionSummary,
} from "./pipeline/symbolic-evaluation/index.js";
export type {
  ClassContextAnalysis,
  ClassDefinitionAnalysis,
  ClassDefinitionSelectorKind,
  ClassReferenceAnalysis,
  ClassReferenceExpressionKind,
  ClassReferenceMatchRelation,
  ClassReferenceOrigin,
  ComponentAnalysis,
  ComponentRenderRelation,
  CssModuleLocalsConvention,
  CssModuleImportAnalysis,
  CssModuleMemberMatchRelation,
  CssModuleMemberReferenceAnalysis,
  CssModuleReferenceDiagnosticAnalysis,
  ModuleImportRelation,
  ProjectEvidenceId,
  ProviderClassSatisfactionRelation,
  RenderSubtreeAnalysis,
  SelectorBranchAnalysis,
  SelectorMatchRelation,
  SelectorQueryAnalysis,
  SourceFileAnalysis,
  StaticallySkippedClassReferenceAnalysis,
  StylesheetAnalysis,
  StylesheetOrigin,
  StylesheetReachabilityRelation,
  UnsupportedClassReferenceAnalysis,
} from "./pipeline/project-evidence/index.js";
export type {
  ProjectSelectorBranchProjection,
  ProjectSelectorProjectionResult,
  ProjectSelectorQueryProjection,
  ProjectSelectorScopedReachability,
  SelectorBranchMatch,
  SelectorBranchRequirement,
  SelectorBranchReachability,
  SelectorElementMatch,
  SelectorMatchCertainty,
  SelectorRequirementCombinator,
  SelectorRequirementStep,
  SelectorReachabilityDiagnostic,
  SelectorReachabilityResult,
  SelectorReachabilityStatus,
  SelectorSubjectRequirement,
} from "./pipeline/selector-reachability/index.js";
export type {
  ClassConsumerSummary,
  ClassOwnershipCompatibilityEvidenceKind,
  ClassDefinitionConsumerEvidence,
  ClassOwnershipEvidence,
  OwnershipCandidateId,
  OwnershipCandidateOwnerKind,
  OwnershipCandidateReason,
  OwnershipCandidateTargetKind,
  OwnershipClassification,
  OwnershipClassificationId,
  OwnershipClassificationTargetKind,
  OwnershipConsumptionKind,
  OwnershipConsumerAvailability,
  OwnershipDiagnosticTargetKind,
  OwnershipEvidenceId,
  OwnershipEvidenceKind,
  OwnershipInferenceDiagnostic,
  OwnershipInferenceDiagnosticCode,
  OwnershipInferenceDiagnosticId,
  OwnershipInferenceIndexes,
  OwnershipInferenceInput,
  OwnershipInferenceMeta,
  OwnershipInferenceOptions,
  OwnershipInferenceResult,
  StyleClassificationEvidence,
  StyleOwnerCandidate,
  StylesheetOwnershipBroadness,
  StylesheetOwnershipEvidence,
} from "./pipeline/ownership-inference/index.js";
export type {
  ProjectEvidenceAssemblyInput,
  ProjectEvidenceAssemblyMeta,
  ProjectEvidenceAssemblyResult,
  ProjectEvidenceDiagnostic,
  ProjectEvidenceDiagnosticCode,
  ProjectEvidenceDiagnosticId,
  ProjectEvidenceDiagnosticTargetKind,
  ProjectEvidenceEntities,
  ProjectEvidenceIndexes,
  ProjectEvidenceRelations,
} from "./pipeline/project-evidence/index.js";
